### ISSUE TITLE
Deploy milestone 0.6.0

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oe_geoutils#16]
Gelieve aan te vinken welke voorwaarden van toepassing zijn:

- [ ] Er zijn aanpassingen in production.ini
- [ ] Er zijn aanpassingen aan ES index
- [ ] Er zijn alembic upgrades
- [ ] Er dienen brieven worden toegevoegd op de dgen
- [x] Deze milestone is afhankelijkheid van deployments andere projecten. Zo ja, welke (Applicatie (versie)):
      - oe_utils: 0.12.0
